// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ScrollFadeController from "./scroll_fade_controller"
application.register("scroll-fade", ScrollFadeController)

import PhoneInputController from "./phone_input_controller"
application.register("phone-input", PhoneInputController)

import TableSortController from "./table_sort_controller"
application.register("table-sort", TableSortController)

import VerificationCodeController from "./verification_code_controller"
application.register("verification-code", VerificationCodeController)

import SubscriptionController from "./subscription_controller"
application.register("subscription", SubscriptionController)