default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# PostgreSQL configuration for production
postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.dig(:database, :host) || "localhost" %>
  database: <%= Rails.application.credentials.dig(:database, :database) || "zenmail_production" %>
  username: <%= Rails.application.credentials.dig(:database, :username) || "postgres" %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>

development:
  adapter: postgresql
  encoding: unicode
  database: zenmail_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["ZENMAIL_DB_USERNAME"] || "postgres" %>
  password: <%= ENV["ZENMAIL_DB_PASSWORD"] || "" %>
  host: <%= ENV["ZENMAIL_DB_HOST"] || "localhost" %>
  port: <%= ENV["ZENMAIL_DB_PORT"] || 5432 %>
  queue:
    <<: *default
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  encoding: unicode
  database: zenmail_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["ZENMAIL_DB_USERNAME"] || "postgres" %>
  password: <%= ENV["ZENMAIL_DB_PASSWORD"] || "" %>
  host: <%= ENV["ZENMAIL_DB_HOST"] || "localhost" %>
  port: <%= ENV["ZENMAIL_DB_PORT"] || 5432 %>
  queue:
    <<: *default
    database: storage/test_queue.sqlite3
    migrations_paths: db/queue_migrate


# Store production database in PostgreSQL
production:
  primary:
    <<: *postgresql
  cache:
    <<: *postgresql
    migrations_paths: db/cache_migrate
  queue:
    <<: *postgresql
    migrations_paths: db/queue_migrate
  cable:
    <<: *postgresql
    migrations_paths: db/cable_migrate